#!/usr/bin/env python
from JAK.Application import JWebApp

url = "https://gab.com"
icon = "/usr/share/icons/breeze/apps/48/gab.png"

webapp = JWebApp(title="Gab", icon=icon, online=True, web_contents=url)

webapp.run()
