#!/usr/bin/sudo /bin/bash

basenames=$(wget -qO - https://appimage.github.io/apps | grep -Eo "<a href=\".*\">" | grep -v "github.com" | grep -v "twitter" | grep -v "opensuse" | grep -v "feed.xml" | cut -d "\"" -f2 | cut -d '/' -f2 | sed "/apps/d" | sed "/wishlist/d" | sed "/help/d" | sed "/^$/d" | tail -n+2)

#AppImage database directory
if [ ! -d /var/db/imgmerge ]; then
  mkdir -p /var/db/imgmerge
fi

#AppImage install directory
if [ ! -d /Applications ]; then
  mkdir /Applications
fi

if [ "$1" == "sync" ]; then
  #Build AppImage database
  for i in $basenames; do
    wget -qO - https://appimage.github.io/$i | grep "button green" | cut -d "\"" -f2
  done | tee /var/db/imgmerge/appimagelist
elif [ "$1" == "search" ]; then
  shift
  pkgs="$(for i in $@; do grep "$i" /var/db/imgmerge/appimagelist; done)"
  echo $pkgs
elif [ "$1" == "install" ]; then
  shift
  pkgs="$(for i in $@; do grep "$i" /var/db/imgmerge/appimagelist; done)"
  if [ -z "$pkgs" ]; then
    echo "Error: empty package list" && exit 137
  else
    for i in $pkgs; do
      domain=$(echo $i | cut -d "/" -f3)
      if [ "$domain" == "download.opensuse.org" ]; then
        appimage=https://$domain$(wget -qO - $i | grep "mirrorbrain-btn" | cut -d\" -f2 )
      else
        appimage=https://$domain$(wget -qO - $i | grep -v "\.com" | grep -v "\.org" | grep -Eo "/.*\.AppImage" | head -n1)
      fi
      wget -O /Applications/$(echo $i | cut -d / -f5).AppImage $appimage
      chmod a+x /Applications/$(echo $i | cut -d / -f5).AppImage
    done
  fi
elif [ "$1" == "remove" ]; then
  shift
  for i in $(ls /Applications | grep $@); do
    rm -f /Applications/$i
  done
else
  echo "Usage: imgmerge [sync|search|install <packagenames>|remove <packagenames>]"
  echo "    sync: Build database of AppImages"
  echo "    search: Search for an AppImage in the database"
  echo "    install <packagenames>: Install AppImage by name"
  echo "    remove <packagenames>: Delete AppImage"
fi
    
      
    
