subarch: amd64
version_stamp: installer-latest
target: livecd-stage1
rel_type: default
profile: default/linux/amd64/17.1/desktop/gnome/systemd
snapshot: latest
source_subpath: default/livecd-stage1-amd64-installer-latest
portage_confdir: /opt/TriggerLinux/portage
portage_overlay: /var/lib/layman/triggerlinux-overlay

livecd/use:
	-bindist
	bash-completion
	bzip2
	idm
	ipv6
	mmx
	sse
	sse2
	urandom
livecd/packages:
	acct-group/adm
	acct-group/audio
	acct-group/cdrom
	acct-group/dialout
	acct-group/disk
	acct-group/input
	acct-group/kmem
	acct-group/kvm
	acct-group/lp
	acct-group/messagebus
	acct-group/plugdev
	acct-group/render
	acct-group/systemd-coredump
	acct-group/systemd-journal
	acct-group/systemd-journal-remote
	acct-group/systemd-network
	acct-group/systemd-resolve
	acct-group/systemd-timesync
	acct-group/tape
	acct-group/tty
	acct-group/utmp
	acct-group/video
	acct-group/wheel
	acct-user/messagebus
	acct-user/systemd-coredump
	acct-user/systemd-journal-remote
	acct-user/systemd-network
	acct-user/systemd-resolve
	acct-user/systemd-timesync
	app-accessibility/at-spi2-atk
	app-accessibility/at-spi2-core
	app-admin/apache-tools
	app-admin/calamares
	app-admin/eselect
	app-admin/gamin
	app-admin/gam-server
	app-admin/perl-cleaner
	app-admin/sudo
	app-admin/system-config-printer
	app-arch/brotli
	app-arch/bzip2
	app-arch/cpio
	app-arch/file-roller
	app-arch/gcab
	app-arch/gnome-autoar
	app-arch/gzip
	app-arch/lbzip2
	app-arch/libarchive
	app-arch/lz4
	app-arch/pax
	app-arch/rpm2targz
	app-arch/tar
	app-arch/unzip
	app-arch/xz-utils
	app-arch/zstd
	app-cdr/brasero
	app-cdr/cdrtools
	app-crypt/argon2
	app-crypt/gcr
	app-crypt/gentoo-keys
	app-crypt/gnupg
	app-crypt/gpgme
	app-crypt/libb2
	app-crypt/libsecret
	app-crypt/mhash
	app-crypt/mit-krb5
	app-crypt/openpgp-keys-gentoo-release
	app-crypt/p11-kit
	app-crypt/pinentry
	app-crypt/rhash
	app-crypt/seahorse
	app-crypt/shash
	app-dicts/gnome-dictionary
	app-doc/xmltoman
	app-editors/gedit
	app-editors/nano
	app-eselect/eselect-cblas
	app-eselect/eselect-cdparanoia
	app-eselect/eselect-fontconfig
	app-eselect/eselect-gnome-shell-extensions
	app-eselect/eselect-lib-bin-symlink
	app-eselect/eselect-mpg123
	app-eselect/eselect-notify-send
	app-eselect/eselect-opengl
	app-eselect/eselect-pinentry
	app-eselect/eselect-python
	app-eselect/eselect-ruby
	app-i18n/ibus
	app-i18n/unicode-cldr
	app-i18n/unicode-data
	app-i18n/unicode-emoji
	app-misc/ca-certificates
	app-misc/c_rehash
	app-misc/editor-wrapper
	app-misc/geoclue
	app-misc/jq
	app-misc/mime-types
	app-misc/pax-utils
	app-misc/tracker
	app-misc/tracker-miners
	app-misc/zisofs-tools
	app-portage/eix
	app-portage/elt-patches
	app-portage/gemato
	app-portage/layman
	app-portage/portage-utils
	app-shells/bash
	app-shells/push
	app-shells/quoter
	app-text/asciidoc
	app-text/build-docbook-catalog
	app-text/docbook-dsssl-stylesheets
	app-text/docbook-sgml-dtd
	app-text/docbook-sgml-dtd
	app-text/docbook-sgml-dtd
	app-text/docbook-sgml-dtd
	app-text/docbook-sgml-dtd
	app-text/docbook-sgml-dtd
	app-text/docbook-sgml-utils
	app-text/docbook-xml-dtd
	app-text/docbook-xml-dtd
	app-text/docbook-xml-dtd
	app-text/docbook-xml-dtd
	app-text/docbook-xml-dtd
	app-text/docbook-xml-simple-dtd
	app-text/docbook-xml-simple-dtd
	app-text/docbook-xsl-stylesheets
	app-text/enchant
	app-text/evince
	app-text/ghostscript-gpl
	app-text/gnome-doc-utils
	app-text/gspell
	app-text/gtkspell
	app-text/hunspell
	app-text/iso-codes
	app-text/libpaper
	app-text/manpager
	app-text/mupdf
	app-text/openjade
	app-text/opensp
	app-text/po4a
	app-text/poppler
	app-text/poppler-data
	app-text/qpdf
	app-text/scrollkeeper-dtd
	app-text/sgml-common
	app-text/xmlto
	app-text/yelp-tools
	dev-cpp/atkmm
	dev-cpp/cairomm
	dev-cpp/glibmm
	dev-cpp/gtkmm
	dev-cpp/gtkmm
	dev-cpp/pangomm
	dev-db/sqlite
	dev-lang/lua
	dev-lang/mujs
	dev-lang/nasm
	dev-lang/orc
	dev-lang/perl
	dev-lang/python
	dev-lang/python
	dev-lang/python-exec
	dev-lang/ruby
	dev-lang/ruby
	dev-lang/sassc
	dev-lang/spidermonkey
	dev-lang/swig
	dev-lang/vala
	dev-lang/yasm
	dev-libs/appstream-glib
	dev-libs/apr
	dev-libs/apr-util
	dev-libs/atk
	dev-libs/boehm-gc
	dev-libs/boost
	dev-libs/check
	dev-libs/cyrus-sasl
	dev-libs/dbus-glib
	dev-libs/double-conversion
	dev-libs/elfutils
	dev-libs/ell
	dev-libs/expat
	dev-libs/folks
	dev-libs/fribidi
	dev-libs/gjs
	dev-libs/glib
	dev-libs/gmp
	dev-libs/gobject-introspection
	dev-libs/gobject-introspection-common
	dev-libs/gom
	dev-libs/hyphen
	dev-libs/icu
	dev-libs/iniparser
	dev-libs/json-c
	dev-libs/json-glib
	dev-libs/libaio
	dev-libs/libassuan
	dev-libs/libatasmart
	dev-libs/libatomic_ops
	dev-libs/libbsd
	dev-libs/libburn
	dev-libs/libbytesize
	dev-libs/libcdio
	dev-libs/libcdio-paranoia
	dev-libs/libcroco
	dev-libs/libdaemon
	dev-libs/libdazzle
	dev-libs/libev
	dev-libs/libevdev
	dev-libs/libffi
	dev-libs/libgamin
	dev-libs/libgcrypt
	dev-libs/libgdata
	dev-libs/libgee
	dev-libs/libgnome-games-support
	dev-libs/libgpg-error
	dev-libs/libgudev
	dev-libs/libgusb
	dev-libs/libgweather
	dev-libs/libical
	dev-libs/libinput
	dev-libs/libisofs
	dev-libs/libksba
	dev-libs/libltdl
	dev-libs/libmspack
	dev-libs/libnatspec
	dev-libs/libnl
	dev-libs/libpcre2
	dev-libs/libpcre
	dev-libs/libpeas
	dev-libs/libpipeline
	dev-libs/libpthread-stubs
	dev-libs/libpwquality
	dev-libs/libsass
	dev-libs/libsigc++
	dev-libs/libtasn1
	dev-libs/libunistring
	dev-libs/libusb
	dev-libs/libuv
	dev-libs/libverto
	dev-libs/libxml2
	dev-libs/libxmlb
	dev-libs/libxslt
	dev-libs/libyaml
	dev-libs/lzo
	dev-libs/mpc
	dev-libs/mpfr
	dev-libs/nettle
	dev-libs/newt
	dev-libs/npth
	dev-libs/nspr
	dev-libs/nss
	dev-libs/openssl
	dev-libs/popt
	dev-libs/qqwing
	dev-libs/rocm-opencl-runtime
	dev-libs/totem-pl-parser
	dev-libs/vala-common
	dev-lua/lpeg
	dev-lua/LuaBitOp
	dev-lua/luaexpat
	dev-lua/luajson
	dev-lua/luasocket
	dev-util/triggerlinux-autobuilder
	dev-perl/Authen-SASL
	dev-perl/Canary-Stability
	dev-perl/common-sense
	dev-perl/Crypt-PasswdMD5
	dev-perl/Digest-HMAC
	dev-perl/Digest-SHA1
	dev-perl/Encode-Locale
	dev-perl/Error
	dev-perl/File-BaseDir
	dev-perl/File-DesktopEntry
	dev-perl/File-Listing
	dev-perl/File-MimeInfo
	dev-perl/HTML-Parser
	dev-perl/HTML-Tagset
	dev-perl/HTTP-Cookies
	dev-perl/HTTP-Daemon
	dev-perl/HTTP-Date
	dev-perl/HTTP-Message
	dev-perl/HTTP-Negotiate
	dev-perl/IO-HTML
	dev-perl/IO-Socket-INET6
	dev-perl/IO-Socket-SSL
	dev-perl/IPC-System-Simple
	dev-perl/JSON
	dev-perl/JSON-XS
	dev-perl/libintl-perl
	dev-perl/libwww-perl
	dev-perl/Locale-gettext
	dev-perl/LWP-MediaTypes
	dev-perl/LWP-Protocol-https
	dev-perl/MailTools
	dev-perl/Module-Build
	dev-perl/Net-DBus
	dev-perl/Net-HTTP
	dev-perl/Net-SSLeay
	dev-perl/SGMLSpm
	dev-perl/Socket6
	dev-perl/Sub-Name
	dev-perl/TermReadKey
	dev-perl/Text-CharWidth
	dev-perl/Text-Iconv
	dev-perl/Text-Unidecode
	dev-perl/Text-WrapI18N
	dev-perl/Tie-IxHash
	dev-perl/TimeDate
	dev-perl/Try-Tiny
	dev-perl/Types-Serialiser
	dev-perl/Unicode-EastAsianWidth
	dev-perl/URI
	dev-perl/WWW-RobotRules
	dev-perl/X11-Protocol
	dev-perl/XML-Parser
	dev-perl/XML-Twig
	dev-perl/XML-XPath
	dev-python/asn1crypto
	dev-python/bz2file
	dev-python/certifi
	dev-python/cffi
	dev-python/chardet
	dev-python/cryptography
	dev-python/cython
	dev-python/dbus-python
	dev-python/enum34
	dev-python/extras
	dev-python/fixtures
	dev-python/idna
	dev-python/ipaddress
	dev-python/linecache2
	dev-python/lxml
	dev-python/m2crypto
	dev-python/mako
	dev-python/markupsafe
	dev-python/mimeparse
	dev-python/olefile
	dev-python/pbr
	dev-python/pillow
	=dev-python/pip-9999
	dev-python/ply
	dev-python/pyblake2
	dev-python/pycairo
	dev-python/pycparser
	dev-python/pycups
	dev-python/pydecomp
	dev-python/pygobject
	dev-python/pyopenssl
	dev-python/pyrsistent
	dev-python/PySocks
	dev-python/pyxattr
	dev-python/requests
	dev-python/setuptools
	dev-python/six
	dev-python/snakeoil
	dev-python/subunit
	dev-python/testtools
	dev-python/traceback2
	dev-python/typing
	dev-python/unittest2
	dev-python/urllib3
	dev-qt/qtchooser
	dev-qt/qtcore
	dev-qt/qtdbus
	dev-qt/qtgui
	dev-qt/qtsvg
	dev-qt/qttest
	dev-qt/qtwidgets
	dev-qt/qtxml
	dev-ruby/did_you_mean
	dev-ruby/did_you_mean
	dev-ruby/json
	dev-ruby/kpeg
	dev-ruby/minitest
	dev-ruby/net-telnet
	dev-ruby/power_assert
	dev-ruby/racc
	dev-ruby/rake
	dev-ruby/rdoc
	dev-ruby/rubygems
	dev-ruby/test-unit
	dev-ruby/xmlrpc
	dev-util/boost-build
	dev-util/catalyst
	dev-util/cmake
	dev-util/cmocka
	dev-util/cppunit
	dev-util/desktop-file-utils
	dev-util/gdbus-codegen
	dev-util/glib-utils
	dev-util/gperf
	dev-util/gtk-doc-am
	dev-util/gtk-update-icon-cache
	dev-util/intltool
	dev-util/itstool
	dev-util/meson
	dev-util/ninja
	dev-util/pkgconf
	dev-util/ragel
	dev-util/re2c
	dev-vcs/git
	games-arcade/gnome-nibbles
	games-arcade/gnome-robots
	games-board/four-in-a-row
	games-board/gnome-chess
	games-board/gnome-mahjongg
	games-board/gnome-mines
	games-board/iagno
	games-board/tali
	games-puzzle/five-or-more
	games-puzzle/gnome-klotski
	games-puzzle/gnome-sudoku
	games-puzzle/gnome-taquin
	games-puzzle/gnome-tetravex
	games-puzzle/hitori
	games-puzzle/lightsoff
	games-puzzle/quadrapassel
	games-puzzle/swell-foop
	gnome-base/dconf
	gnome-base/dconf-editor
	gnome-base/gdm
	gnome-base/gnome
	gnome-base/gnome-common
	gnome-base/gnome-control-center
	gnome-base/gnome-core-apps
	gnome-base/gnome-core-libs
	gnome-base/gnome-desktop
	gnome-base/gnome-extra-apps
	gnome-base/gnome-keyring
	gnome-base/gnome-menus
	gnome-base/gnome-session
	gnome-base/gnome-settings-daemon
	gnome-base/gnome-shell
	gnome-base/gsettings-desktop-schemas
	gnome-base/gvfs
	gnome-base/libgnomekbd
	gnome-base/libgtop
	gnome-base/librsvg
	gnome-base/nautilus
	gnome-extra/chrome-gnome-shell
	gnome-extra/evolution-data-server
	gnome-extra/evolution-ews
	gnome-extra/gnome-calculator
	gnome-extra/gnome-calendar
	gnome-extra/gnome-characters
	gnome-extra/gnome-clocks
	gnome-extra/gnome-color-manager
	gnome-extra/gnome-contacts
	gnome-extra/gnome-shell-extension-dash-to-panel
	gnome-extra/gnome-shell-extension-desktop-icons
	gnome-extra/gnome-shell-extensions
	gnome-extra/gnome-system-monitor
	gnome-extra/gnome-tweaks
	gnome-extra/gnome-user-docs
	gnome-extra/gnome-user-share
	gnome-extra/gnome-weather
	gnome-extra/gucharmap
	gnome-extra/nautilus-sendto
	gnome-extra/nm-applet
	gnome-extra/polkit-gnome
	gnome-extra/sushi
	gnome-extra/yelp
	gnome-extra/yelp-xsl
	gnome-extra/zenity
	mail-client/evolution
	mail-filter/bogofilter
	mail-mta/nullmailer
	media-fonts/cantarell
	media-fonts/encodings
	media-fonts/font-util
	media-fonts/liberation-fonts
	media-fonts/urw-fonts
	media-gfx/eog
	media-gfx/exiv2
	media-gfx/gnome-font-viewer
	media-gfx/gnome-photos
	media-gfx/gnome-screenshot
	media-gfx/graphite2
	media-gfx/shotwell
	media-libs/a52dec
	media-libs/alsa-lib
	media-libs/audiofile
	media-libs/babl
	media-libs/clutter
	media-libs/clutter-gst
	media-libs/clutter-gtk
	media-libs/cogl
	media-libs/faad2
	media-libs/flac
	media-libs/fontconfig
	media-libs/freeglut
	media-libs/freetype
	media-libs/gd
	media-libs/gegl
	media-libs/gexiv2
	media-libs/giflib
	media-libs/glu
	media-libs/graphene
	media-libs/grilo
	media-libs/gsound
	media-libs/gst-plugins-bad
	media-libs/gst-plugins-base
	media-libs/gst-plugins-good
	media-libs/gst-plugins-ugly
	media-libs/gstreamer
	media-libs/harfbuzz
	media-libs/jbig2dec
	media-libs/lcms
	media-libs/libcanberra
	media-libs/libdca
	media-libs/libdiscid
	media-libs/libdvdcss
	media-libs/libdvdnav
	media-libs/libdvdread
	media-libs/libepoxy
	media-libs/libexif
	media-libs/libgphoto2
	media-libs/libjpeg-turbo
	media-libs/libmediaart
	media-libs/libmms
	media-libs/libmpeg2
	media-libs/libogg
	media-libs/libpng
	media-libs/libquvi
	media-libs/libquvi-scripts
	media-libs/libraw
	media-libs/libsdl
	media-libs/libsndfile
	media-libs/libtheora
	media-libs/libv4l
	media-libs/libvorbis
	media-libs/libvpx
	media-libs/libwebp
	media-libs/mesa
	media-libs/musicbrainz
	media-libs/openjpeg
	media-libs/opus
	media-libs/sbc
	media-libs/speexdsp
	media-libs/taglib
	media-libs/tiff
	media-libs/webrtc-audio-processing
	media-libs/woff2
	media-libs/x264
	media-plugins/alsa-plugins
	media-plugins/grilo-plugins
	media-plugins/gst-plugins-a52dec
	media-plugins/gst-plugins-cdparanoia
	media-plugins/gst-plugins-dts
	media-plugins/gst-plugins-dvdread
	media-plugins/gst-plugins-faad
	media-plugins/gst-plugins-flac
	media-plugins/gst-plugins-gdkpixbuf
	media-plugins/gst-plugins-gtk
	media-plugins/gst-plugins-jpeg
	media-plugins/gst-plugins-libmms
	media-plugins/gst-plugins-meta
	media-plugins/gst-plugins-mpeg2dec
	media-plugins/gst-plugins-mpg123
	media-plugins/gst-plugins-opus
	media-plugins/gst-plugins-pulse
	media-plugins/gst-plugins-resindvd
	media-plugins/gst-plugins-soup
	media-plugins/gst-plugins-taglib
	media-plugins/gst-plugins-v4l2
	media-plugins/gst-plugins-vpx
	media-plugins/gst-plugins-x264
	media-sound/cdparanoia
	media-sound/gnome-music
	media-sound/mpg123
	media-sound/pulseaudio
	media-sound/rhythmbox
	media-sound/sound-juicer
	media-video/cheese
	media-video/gnome-video-effects
	media-video/totem
	net-dialup/ppp
	net-dialup/ppp-scripts
	net-dns/avahi
	net-dns/libidn
	net-dns/libidn2
	net-firewall/iptables
	net-fs/cifs-utils
	net-fs/samba
	net-im/telepathy-mission-control
	net-libs/glib-networking
	net-libs/gnome-online-accounts
	net-libs/gnutls
	net-libs/gtk-vnc
	net-libs/libasyncns
	net-libs/libgfbgraph
	net-libs/libgrss
	net-libs/libmbim
	net-libs/libmnl
	net-libs/libndp
	net-libs/libnsl
	net-libs/liboauth
	net-libs/libproxy
	net-libs/libpsl
	net-libs/libqmi
	net-libs/libsoup
	net-libs/libtirpc
	net-libs/libzapojit
	net-libs/neon
	net-libs/rest
	net-libs/rpcsvc-proto
	net-libs/telepathy-glib
	net-libs/webkit-gtk
	net-mail/mailbase
	net-misc/curl
	net-misc/dhcp
	net-misc/gnome-online-miners
	net-misc/iputils
	net-misc/mobile-broadband-provider-info
	net-misc/modemmanager
	net-misc/networkmanager
	net-misc/openssh
	net-misc/rsync
	net-misc/vinagre
	net-misc/vino
	net-misc/wget
	net-nds/openldap
	net-print/cups
	net-print/cups-filters
	net-print/cups-pk-helper
	net-print/hplip
	net-wireless/bluez
	net-wireless/crda
	net-wireless/gnome-bluetooth
	net-wireless/wireless-regdb
	net-wireless/wpa_supplicant
	perl-core/File-Temp
	sci-geosciences/geocode-glib
	sci-libs/gsl
	sys-apps/accountsservice
	sys-apps/acl
	sys-apps/attr
	sys-apps/baobab
	sys-apps/baselayout
	sys-apps/bubblewrap
	sys-apps/busybox
	sys-apps/coreutils
	sys-apps/dbus
	sys-apps/debianutils
	sys-apps/diffutils
	sys-apps/file
	sys-apps/findutils
	sys-apps/fwupd
	sys-apps/gawk
	sys-apps/gentoo-functions
	sys-apps/gentoo-systemd-integration
	sys-apps/gnome-disk-utility
	sys-apps/gptfdisk
	sys-apps/grep
	sys-apps/groff
	sys-apps/help2man
	sys-apps/hwids
	sys-apps/install-xattr
	sys-apps/iproute2
	sys-apps/kbd
	sys-apps/keyutils
	sys-apps/kmod
	sys-apps/less
	sys-apps/man-db
	sys-apps/man-pages
	sys-apps/man-pages-posix
	sys-apps/net-tools
	sys-apps/osinfo-db
	sys-apps/osinfo-db-tools
	sys-apps/paxctl
	sys-apps/pciutils
	sys-apps/portage
	sys-apps/sandbox
	sys-apps/sed
	sys-apps/shadow
	sys-apps/systemd
	sys-apps/tcp-wrappers
	sys-apps/texinfo
	sys-apps/util-linux
	sys-apps/which
	sys-apps/xdg-desktop-portal
	sys-auth/pambase
	sys-auth/polkit
	sys-block/gparted
	sys-block/parted
	sys-block/thin-provisioning-tools
	sys-boot/efibootmgr
	sys-boot/gnu-efi
	=sys-boot/grub-9999
	=sys-boot/plymouth-9999
	sys-boot/syslinux
	sys-devel/autoconf
	sys-devel/autoconf
	sys-devel/autoconf-archive
	sys-devel/autoconf-wrapper
	sys-devel/automake
	sys-devel/automake
	sys-devel/automake-wrapper
	sys-devel/bc
	sys-devel/binutils
	sys-devel/binutils-config
	sys-devel/bison
	sys-devel/flex
	sys-devel/gcc
	sys-devel/gcc-config
	sys-devel/gettext
	sys-devel/gnuconfig
	sys-devel/libtool
	sys-devel/llvm
	sys-devel/llvm-common
	sys-devel/m4
	sys-devel/make
	sys-devel/patch
	sys-fs/btrfs-progs
	sys-fs/cryptsetup
	sys-fs/dosfstools
	sys-fs/e2fsprogs
	sys-fs/fuse
	sys-fs/fuse-common
	sys-fs/lvm2
	sys-fs/mtools
	sys-fs/squashfs-tools
	sys-fs/udev-init-scripts
	sys-fs/udisks
	sys-kernel/genkernel-next
	sys-kernel/linux-firmware
	sys-kernel/linux-headers
	sys-libs/binutils-libs
	sys-libs/cracklib
	sys-libs/db
	sys-libs/e2fsprogs-libs
	sys-libs/efivar
	sys-libs/gdbm
	sys-libs/glibc
	sys-libs/gpm
	sys-libs/kpmcore
	sys-libs/ldb
	sys-libs/libblockdev
	sys-libs/libcap
	sys-libs/libcap-ng
	sys-libs/libosinfo
	sys-libs/libseccomp
	sys-libs/mtdev
	sys-libs/ncurses
	sys-libs/pam
	sys-libs/readline
	sys-libs/slang
	sys-libs/talloc
	sys-libs/tdb
	sys-libs/tevent
	sys-libs/timezone-data
	sys-libs/zlib
	sys-power/acpid
	sys-power/upower
	sys-process/procps
	sys-process/psmisc
	virtual/acl
	virtual/awk
	virtual/cdrtools
	virtual/dev-manager
	virtual/editor
	virtual/eject
	virtual/fam
	virtual/freedesktop-icon-theme
	virtual/glu
	virtual/jpeg
	virtual/krb5
	virtual/libc
	virtual/libelf
	virtual/libffi
	virtual/libgudev
	virtual/libiconv
	virtual/libintl
	virtual/libudev
	virtual/libusb
	virtual/logger
	virtual/man
	virtual/modutils
	virtual/mta
	virtual/notification-daemon
	virtual/opengl
	virtual/os-headers
	virtual/package-manager
	virtual/pager
	virtual/pam
	virtual/perl-Carp
	virtual/perl-Compress-Raw-Bzip2
	virtual/perl-Compress-Raw-Zlib
	virtual/perl-CPAN-Meta
	virtual/perl-CPAN-Meta-YAML
	virtual/perl-Data-Dumper
	virtual/perl-Digest
	virtual/perl-Digest-MD5
	virtual/perl-Digest-SHA
	virtual/perl-Encode
	virtual/perl-Exporter
	virtual/perl-ExtUtils-CBuilder
	virtual/perl-ExtUtils-Install
	virtual/perl-ExtUtils-MakeMaker
	virtual/perl-ExtUtils-Manifest
	virtual/perl-ExtUtils-ParseXS
	virtual/perl-File-Path
	virtual/perl-File-Spec
	virtual/perl-File-Temp
	virtual/perl-Getopt-Long
	virtual/perl-IO
	virtual/perl-IO-Compress
	virtual/perl-IO-Socket-IP
	virtual/perl-JSON-PP
	virtual/perl-libnet
	virtual/perl-MIME-Base64
	virtual/perl-Module-Metadata
	virtual/perl-parent
	virtual/perl-Parse-CPAN-Meta
	virtual/perl-Perl-OSType
	virtual/perl-podlators
	virtual/perl-Scalar-List-Utils
	virtual/perl-Storable
	virtual/perl-Test-Harness
	virtual/perl-Text-ParseWords
	virtual/perl-Time-HiRes
	virtual/perl-Time-Local
	virtual/perl-version
	virtual/perl-XSLoader
	virtual/pkgconfig
	virtual/python-enum34
	virtual/python-ipaddress
	virtual/python-typing
	virtual/rubygems
	virtual/service-manager
	virtual/shadow
	virtual/ssh
	virtual/tmpfiles
	virtual/ttf-fonts
	virtual/udev
	virtual/w3m
	virtual/yacc
	www-apache/mod_dnssd
	www-client/w3m
	www-servers/apache
	x11-apps/iceauth
	x11-apps/mkfontscale
	x11-apps/rgb
	x11-apps/xauth
	x11-apps/xhost
	x11-apps/xinit
	x11-apps/xkbcomp
	x11-apps/xprop
	x11-apps/xrdb
	x11-apps/xset
	x11-base/xcb-proto
	x11-base/xorg-drivers
	x11-base/xorg-proto
	x11-base/xorg-server
	x11-drivers/xf86-input-keyboard
	x11-drivers/xf86-input-libinput
	x11-drivers/xf86-input-mouse
	x11-drivers/xf86-video-amdgpu
	x11-drivers/xf86-video-ati
	x11-drivers/xf86-video-dummy
	x11-drivers/xf86-video-fbdev
	x11-drivers/xf86-video-intel
	x11-drivers/xf86-video-nouveau
	x11-drivers/xf86-video-vesa
	x11-libs/cairo
	x11-libs/colord-gtk
	x11-libs/gdk-pixbuf
	x11-libs/gtk+
	x11-libs/gtk+
	x11-libs/gtksourceview
	x11-libs/libdrm
	x11-libs/libfontenc
	x11-libs/libICE
	x11-libs/libnotify
	x11-libs/libpciaccess
	x11-libs/libSM
	x11-libs/libwnck
	x11-libs/libX11
	x11-libs/libXau
	x11-libs/libXaw
	x11-libs/libxcb
	x11-libs/libXcomposite
	x11-libs/libXcursor
	x11-libs/libXdamage
	x11-libs/libXdmcp
	x11-libs/libXext
	x11-libs/libXfixes
	x11-libs/libXfont2
	x11-libs/libXft
	x11-libs/libXi
	x11-libs/libXinerama
	x11-libs/libxkbcommon
	x11-libs/libxkbfile
	x11-libs/libxklavier
	x11-libs/libXmu
	x11-libs/libXpm
	x11-libs/libXrandr
	x11-libs/libXrender
	x11-libs/libXres
	x11-libs/libXScrnSaver
	x11-libs/libxshmfence
	x11-libs/libXt
	x11-libs/libXtst
	x11-libs/libXv
	x11-libs/libXxf86vm
	x11-libs/pango
	x11-libs/pixman
	x11-libs/startup-notification
	x11-libs/vte
	x11-libs/xcb-util
	x11-libs/xcb-util-cursor
	x11-libs/xcb-util-image
	x11-libs/xcb-util-keysyms
	x11-libs/xcb-util-renderutil
	x11-libs/xcb-util-wm
	x11-libs/xtrans
	x11-misc/colord
	x11-misc/makedepend
	x11-misc/shared-mime-info
	x11-misc/util-macros
	x11-misc/xbitmaps
	x11-misc/xdg-user-dirs
	x11-misc/xdg-user-dirs-gtk
	x11-misc/xdg-utils
	x11-misc/xkeyboard-config
	x11-terms/gnome-terminal
	x11-themes/adwaita-icon-theme
	x11-themes/arc-icon-theme
	x11-themes/arc-theme
	x11-themes/gnome-backgrounds
	x11-themes/gnome-themes-standard
	x11-themes/gtk-engines-adwaita
	x11-themes/gtk-engines-murrine
	x11-themes/hicolor-icon-theme
	x11-themes/murrine-themes
	x11-themes/sound-theme-freedesktop
	x11-wm/mutter
