#!/usr/bin/env python
from JAK.Application import JWebApp

url = "https://www.minds.com"
icon = "/usr/share/icons/breeze/apps/scalable/minds.svg"

webapp = JWebApp(title="Minds", icon=icon, online=True, web_contents=url)

webapp.run()
